// source: menu_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.menu.v1.SectionsResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.menu.v1.Section');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.menu.v1.SectionsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.menu.v1.SectionsResponse.repeatedFields_, null);
};
goog.inherits(proto.menu.v1.SectionsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.menu.v1.SectionsResponse.displayName = 'proto.menu.v1.SectionsResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.menu.v1.SectionsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.menu.v1.SectionsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.menu.v1.SectionsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.menu.v1.SectionsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.menu.v1.SectionsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    sectionListList: jspb.Message.toObjectList(msg.getSectionListList(),
    proto.menu.v1.Section.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.menu.v1.SectionsResponse}
 */
proto.menu.v1.SectionsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.menu.v1.SectionsResponse;
  return proto.menu.v1.SectionsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.menu.v1.SectionsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.menu.v1.SectionsResponse}
 */
proto.menu.v1.SectionsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.menu.v1.Section;
      reader.readMessage(value,proto.menu.v1.Section.deserializeBinaryFromReader);
      msg.addSectionList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.menu.v1.SectionsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.menu.v1.SectionsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.menu.v1.SectionsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.menu.v1.SectionsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSectionListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.menu.v1.Section.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Section section_list = 1;
 * @return {!Array<!proto.menu.v1.Section>}
 */
proto.menu.v1.SectionsResponse.prototype.getSectionListList = function() {
  return /** @type{!Array<!proto.menu.v1.Section>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.menu.v1.Section, 1));
};


/**
 * @param {!Array<!proto.menu.v1.Section>} value
 * @return {!proto.menu.v1.SectionsResponse} returns this
*/
proto.menu.v1.SectionsResponse.prototype.setSectionListList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.menu.v1.Section=} opt_value
 * @param {number=} opt_index
 * @return {!proto.menu.v1.Section}
 */
proto.menu.v1.SectionsResponse.prototype.addSectionList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.menu.v1.Section, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.menu.v1.SectionsResponse} returns this
 */
proto.menu.v1.SectionsResponse.prototype.clearSectionListList = function() {
  return this.setSectionListList([]);
};


