/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.country.v2.Country');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.country.v2.Currency');
goog.require('proto.country.v2.Language');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.country.v2.Country = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.country.v2.Country.repeatedFields_, null);
};
goog.inherits(proto.country.v2.Country, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.country.v2.Country.displayName = 'proto.country.v2.Country';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.country.v2.Country.repeatedFields_ = [10,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.country.v2.Country.prototype.toObject = function(opt_includeInstance) {
  return proto.country.v2.Country.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.country.v2.Country} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.country.v2.Country.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    code: jspb.Message.getFieldWithDefault(msg, 3, ""),
    pb_native: jspb.Message.getFieldWithDefault(msg, 4, ""),
    currencyList: jspb.Message.toObjectList(msg.getCurrencyList(),
    proto.country.v2.Currency.toObject, includeInstance),
    languageList: jspb.Message.toObjectList(msg.getLanguageList(),
    proto.country.v2.Language.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.country.v2.Country}
 */
proto.country.v2.Country.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.country.v2.Country;
  return proto.country.v2.Country.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.country.v2.Country} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.country.v2.Country}
 */
proto.country.v2.Country.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNative(value);
      break;
    case 10:
      var value = new proto.country.v2.Currency;
      reader.readMessage(value,proto.country.v2.Currency.deserializeBinaryFromReader);
      msg.addCurrency(value);
      break;
    case 11:
      var value = new proto.country.v2.Language;
      reader.readMessage(value,proto.country.v2.Language.deserializeBinaryFromReader);
      msg.addLanguage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.country.v2.Country.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.country.v2.Country.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.country.v2.Country} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.country.v2.Country.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNative();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCurrencyList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      proto.country.v2.Currency.serializeBinaryToWriter
    );
  }
  f = message.getLanguageList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.country.v2.Language.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.country.v2.Country.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.country.v2.Country.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.country.v2.Country.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.country.v2.Country.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string code = 3;
 * @return {string}
 */
proto.country.v2.Country.prototype.getCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.country.v2.Country.prototype.setCode = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string native = 4;
 * @return {string}
 */
proto.country.v2.Country.prototype.getNative = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.country.v2.Country.prototype.setNative = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated Currency currency = 10;
 * @return {!Array<!proto.country.v2.Currency>}
 */
proto.country.v2.Country.prototype.getCurrencyList = function() {
  return /** @type{!Array<!proto.country.v2.Currency>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.country.v2.Currency, 10));
};


/** @param {!Array<!proto.country.v2.Currency>} value */
proto.country.v2.Country.prototype.setCurrencyList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!proto.country.v2.Currency=} opt_value
 * @param {number=} opt_index
 * @return {!proto.country.v2.Currency}
 */
proto.country.v2.Country.prototype.addCurrency = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, proto.country.v2.Currency, opt_index);
};


proto.country.v2.Country.prototype.clearCurrencyList = function() {
  this.setCurrencyList([]);
};


/**
 * repeated Language language = 11;
 * @return {!Array<!proto.country.v2.Language>}
 */
proto.country.v2.Country.prototype.getLanguageList = function() {
  return /** @type{!Array<!proto.country.v2.Language>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.country.v2.Language, 11));
};


/** @param {!Array<!proto.country.v2.Language>} value */
proto.country.v2.Country.prototype.setLanguageList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.country.v2.Language=} opt_value
 * @param {number=} opt_index
 * @return {!proto.country.v2.Language}
 */
proto.country.v2.Country.prototype.addLanguage = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.country.v2.Language, opt_index);
};


proto.country.v2.Country.prototype.clearLanguageList = function() {
  this.setLanguageList([]);
};


